[script]
name = "ASM_bitbank"
normal_name = "ticker_base"
model_name = "AS_base"

[config]
actionWnd = 300000
lifetime = 30000
portion = 50.0
holding_limit = 1.0
tradeWnd = 500
priceWnd = 200
depthWnd = 100
trade_ratio = 0.6
trade_grid = 10
data_groups = 30

[params]
tick = 0.01
gamma = 0.1
alpha = 1.0
sigma = 0.0
k = 0.0
# K = 1.5

[options]
normal = true
is_test = true
only_once = false
trader_limit = 3

[pair_info]
base_c = "XRP"
base_q = 0.0
quote_c = "JPY"
quote_q = 400000.0
holding_rate = 0.4

[market_info]
exchange = "bitbank"
market = "spot"
chain = ""

