[script]
name = "ASM_coinbase"
normal_name = "ticker_base"
model_name = "AS_base"

[config]
actionWnd = 10000
lifetime = 3000
portion = 0.04
holding_limit = 1.0
tradeWnd = 500
priceWnd = 200
depthWnd = 100
trade_ratio = 0.6
trade_grid = 10
data_groups = 30

[params]
tick = 0.1
gamma = 0.1
alpha = 1.0
sigma = 0.0
k = 0.0
# K = 1.5

[options]
normal = true
is_test = true
only_once = false
trader_limit = 3

[pair_info]
base_c = "ETH"
base_q = 0.0
quote_c = "USD"
quote_q = 3000.0
holding_rate = 0.4

[market_info]
exchange = "coinbase"
market = "spot"
chain = ""

