[script]
name = "ASM_huobi_uswap"
normal_name = "ticker_base"
model_name = "AS_base"

[config]
actionWnd = 30000
lifetime = 3000
portion = 0.01
holding_limit = 1.0
tradeWnd = 250
priceWnd = 200
depthWnd = 100
trade_ratio = 0.6
trade_grid = 10
data_groups = 30

[params]
tick = 0.1
gamma = 0.1
alpha = 1.0
sigma = 0.0
k = 0.0
# K = 1.5

[options]
normal = false
is_test = true
only_once = false
trader_limit = 3

[pair_info]
symbol_type = "SWAP_FOREVER"
base_c = "BTC"
base_q = 0.0
quote_c = "USDT"
quote_q = 300.0
quote_limit = 300.0
holding_rate = 0.4
lever_rate = 5

[market_info]
exchange = "huobi"
market = "swap"
chain = ""

